substitutions:
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: "${devicename}"
  name_add_mac_suffix: false
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  variant: esp32
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "20"
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

time:
  - platform: homeassistant

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: "relay"
    name: "Rele"
    output: "relay_output"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    name: "Vypínač"
    pin: GPIO4
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
      then:
        - if:
            condition:
              and:
                - wifi.connected:
                - api.connected:
            then:
              - logger.log: "API připojeno, posílám stav"
            else:
              - switch.toggle: "relay"

  - platform: gpio
    name: "Reset tlačítko"
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "ESP Teplota"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
 
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 12db

  - platform: adc
    name: "Rele Volt"
    pin: GPIO33
    unit_of_measurement: V
    attenuation: 12db
    filters:
      - multiply: 8

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO23
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO18
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "Napětí"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:flash-outline
      filters:
        - clamp:
            min_value: 0
      
    voltage:
      name: "Volt"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
      filters:
        - clamp:
            min_value: 0
            
    power:
      name: "Příkon"
      unit_of_measurement: W
      id: power
      icon: mdi:flash-outline
      filters:
        - clamp:
            min_value: 0
      on_value_range:
        - above: "3600"
          then:
            - switch.turn_off: "relay"
    change_mode_every: 2
    update_interval: 10s

  - platform: total_daily_energy
    name: "Denní spotřeba"
    power_id: power
    filters:
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert

esp32_ble_tracker:
  
status_led:
  pin:
    number: GPIO0
    inverted: true

button:
  - platform: restart
    id: "restart_device"
    name: "Restart"
    entity_category: 'diagnostic'
  - platform: safe_mode
    name: "SafeMode"
    entity_category: 'diagnostic'

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true