# For PCB v0.1.9 with dual core ESP32
substitutions:
  # Relay trip limits
  max_power: "3600.0"
  max_temp: "80.0"

esphome:
  name: "${devicename}"

esp32:
  variant: esp32
  framework:
    type: esp-idf

time:
  - platform: homeassistant

i2c:
  sda: GPIO26
  scl: GPIO25

output:
  - platform: gpio
    id: "relay_output_1"
    pin: GPIO12

  - platform: gpio
    id: "relay_output_2"
    pin: GPIO13

#Shelly Switch Output
switch:
  - platform: output
    id: "relay_1"
    name: "${upper_devicename} rele 1"
    output: "relay_output_1"
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: output
    id: "relay_2"
    name: "${upper_devicename} rele 2"
    output: "relay_output_2"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    name: "${upper_devicename} Vypínač 1"
    pin: GPIO5
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
      then:
        - if:
            condition:
              and:
                - wifi.connected:
                - api.connected:
            then:
              - logger.log: "API připojeno, posílám stav"
            else:
              - switch.toggle: "relay_1"

  #Shelly Switch Input 2
  - platform: gpio
    name: "${upper_devicename} Vypínač 2"
    pin: GPIO18
    #small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
      then:
        - if:
            condition:
              and:
                - wifi.connected:
                - api.connected:
            then:
              - logger.log: "API připojeno, posílám stav"
            else:
              - switch.toggle: "relay_2"

  #reset button on device
  - platform: gpio
    id: "restart_button"
    pin:
      number: GPIO4
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - button.press: "restart_device"
    filters:
      - delayed_on_off: 5ms
    internal: true

sensor:
  # Uptime sensor.
  - platform: uptime
    name: "${upper_devicename} Uptime"
    entity_category: 'diagnostic'
    update_interval: 300s

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: "${upper_devicename} WiFi Signal"
    update_interval: 60s
    entity_category: 'diagnostic'

  #temperature sensor
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${upper_devicename} Teplota"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    entity_category: 'diagnostic'
    calibration:
      #These default values don't seem accurate
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: "relay_1"
          - switch.turn_off: "relay_2"
          - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: "Upozonění od ${upper_devicename}"
                data_template:
                  message: "${upper_devicename} vypnuto, protože překonalo ${max_temp}°C"

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: temp_analog_reading
    pin: GPIO35
    attenuation: 12db
    update_interval: 60s

  #power monitoring
  - platform: ade7953_i2c
    irq_pin: GPIO27 # Prevent overheating by setting this
    voltage:
      name: "${upper_devicename} Volt"
      entity_category: 'diagnostic'
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
    # On the Shelly 2.5 channels are mixed ch1=B ch2=A
    current_a:
      name: "${upper_devicename} Napětí 2"
      entity_category: 'diagnostic'
      unit_of_measurement: A
      accuracy_decimals: 1
      icon: mdi:flash-outline
    current_b:
      name: "${upper_devicename} Napětí 1"
      entity_category: 'diagnostic'
      unit_of_measurement: A
      accuracy_decimals: 1
      icon: mdi:flash-outline
    active_power_a:
      name: "${upper_devicename} Příkon 2"
      id: power_channel_2
      entity_category: 'diagnostic'
      unit_of_measurement: W
      icon: mdi:flash-outline
      filters:
        - multiply: -1
      # active_power_a is normal, so don't multiply by -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: "relay_2"
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: "Upozornění od ${upper_devicename}"
                data_template:
                  message: "${upper_devicename} (2) vypnuto, přesáhlo příkon ${max_power}W"
    active_power_b:
      name: "${upper_devicename} Příkon 1"
      id: power_channel_1
      entity_category: 'diagnostic'
      unit_of_measurement: W
      icon: mdi:flash-outline
      # active_power_b is inverted, so multiply by -1
      filters:
        - multiply: -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: "relay_1"
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: "Upozornění od ${upper_devicename}"
                data_template:
                  message: "${upper_devicename} (1) vypnuto, přesáhlo příkon ${max_power}W"
    update_interval: 30s

  - platform: total_daily_energy
    name: "${upper_devicename} denní spotřeba 1"
    power_id: power_channel_1
  - platform: total_daily_energy
    name: "${upper_devicename} denní spotřeba 2"
    power_id: power_channel_2

status_led:
  pin:
    number: GPIO0
    inverted: true

button:
  - platform: restart
    id: "restart_device"
    name: "${upper_devicename} Restart"
    entity_category: 'diagnostic'
  - platform: safe_mode
    name: "${upper_devicename} SafeMode"
    entity_category: 'diagnostic'
